New local starting server
cyberbotics/webots-server pull request #13
Opened 2022-10-20 06:44 UTC by ygoumaz

This new simple server allows to start Webots from a remote machine. The world and startup parameters are given in a shared folder. 

This server is added for macOS compatibility of `webots_ros2`, so that the Docker container can start Webots on the host machine, but this server could also be used in other situations.

2022-10-20 09:38 UTC, omichel requested changes

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +
PEP8 compliance (flake8):
```suggestion


```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +    #shared_folder_str = shared_folder.decode("utf-8")
Can we remove this line?
```suggestion
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +    arguments = []
Unused:
```suggestion
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +
```suggestion


```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +
```suggestion


```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +            shared_folder = data.decode("utf-8")
```suggestion
            shared_folder = data.decode('utf-8')
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +        print(f"Connected by {addr}")
```suggestion
        print(f'Connection from {addr}')
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                conn.sendall(b"FAIL0")
```suggestion
                conn.sendall(b'FAIL0')
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                print(f"The shared folder '{data_str}' doesn't exist.")
```suggestion
                print(f"The shared folder '{shared_folder}' doesn't exist.", file=sys.stderr)
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                print(f"No world could be found in the shared folder.")
```suggestion
                print('No world could be found in the shared folder.' file=sys.stderr)
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                conn.sendall(b"FAIL2")
```suggestion
                conn.sendall(b'FAIL2')
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                print(f"More than one world was found in the shared folder.")
```suggestion
                print('More than one world was found in the shared folder.' file=sys.stderr)
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +                print(f"Webots was executed successfully.")
```suggestion
                print('Webots was executed successfully.')
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +HOST = ""  # Any host can connect
```suggestion
HOST = ''  # Any host can connect
```

2022-10-20 09:38 UTC, omichel commented on local_simulation_server.py
> +    connection.sendall(b"ACK")
```suggestion
    connection.sendall(b'ACK')
```

2022-10-20 13:14 UTC, ygoumaz commented
Sorry for the high number of unused elements and mistakes in the code. I think an iteration of cleanup that I made was not committed and lost somewhere.

2022-10-20 15:09 UTC, omichel requested changes

2022-10-20 15:09 UTC, omichel commented on local_simulation_server.py
> +import os
We should add a header similar to the other python scripts here with the license and description.

2022-10-20 15:09 UTC, omichel commented on local_simulation_server.py
> +    if(len(worlds) == 0):
```suggestion
    if len(worlds) == 0:
```

2022-10-20 15:09 UTC, omichel commented on local_simulation_server.py
> +    if(len(worlds) > 1):
```suggestion
    if len(worlds) > 1:
```

2022-10-20 15:09 UTC, omichel commented on local_simulation_server.py
> +        if(os.path.isdir(shared_folder)):
```suggestion
    if shared_folder:
        if os.path.isdir(shared_folder):
```

2022-10-26 09:13 UTC, ygoumaz commented
The server is now simpler than before. It doesn't clean the shared folder anymore. Also, it is able to detect if the ROS process died and sends a message to the client once Webots is closed.

2022-10-26 10:06 UTC, omichel reviewed
It looks good to me.

However, as I understand, the user has to launch this local server repeatedly as he tries different things on the ROS side. I believe it would be more convenient for the user if the server would be able to accept a new connection a previous connection has closed, e.g., put everything inside a loop that will loop when the client closes the connection and that could be broken with <kbd>Ctr</kbd> + <kbd>C</kbd>.

2022-10-27 10:51 UTC, ygoumaz commented
The server doesn't shutdown anymore when ROS or Webots exit. Instead we continue to listen for a new session.

In addition, Webots is started with the world and arguments given in the tcp message by the ROS client. I also added the possibility to define WEBOTS_HOME as target installation to run Webots.

2022-10-27 14:15 UTC, omichel requested changes

2022-10-27 14:15 UTC, omichel commented on local_simulation_server.py
> +        message = 'FAIL: Webots could not be found on the host.'
```suggestion
        message = f'FAIL: \'{cmd[0]}\'could not be found on the host.'
```

2022-10-27 14:15 UTC, omichel commented on local_simulation_server.py
> +    world_file = cmd[1]
The world file is not necessarily the first argument, it is usually specified after the options.

2022-10-27 14:15 UTC, omichel commented on local_simulation_server.py
> +
I would not rely on `WEBOTS_HOME` to make things simpler here and not specific to macOS:
```suggestion
```

2022-10-27 14:15 UTC, omichel commented on local_simulation_server.py
> +
We should check that `cmd[0].endswith('webots')` to ensure somebody doesn't send a `rm -rf /` command from the outside.

2022-10-28 07:40 UTC, omichel requested changes
Still a couple of requests...

2022-10-28 07:40 UTC, omichel commented on local_simulation_server.py
> +    world_file = cmd[-1]
We shouldn't assume the world file is at the last position either:
```suggestion
    for argument in cmd:
        if argument.endswith('.wbt')
            world_file = argument
            break
```

2022-10-28 07:40 UTC, omichel commented on local_simulation_server.py
> +    cmd = data.decode('utf-8').split(' ')
abbreviation:
```suggestion
    command= data.decode('utf-8').split(' ')
```

2022-10-28 09:09 UTC, omichel requested changes

2022-10-28 09:09 UTC, omichel commented on local_simulation_server.py
> +PORT = int(sys.argv[1])  # Port to listen on
I would set the port by default to 2000 to match the default value set in `webots_tcp_client.py`.

2022-10-28 16:02 UTC, omichel requested changes

2022-10-28 16:02 UTC, omichel commented on local_simulation_server.py
> +        PORT = sys.argv[1]
Why putting this in the loop, can't we set it earlier?

2022-10-28 16:02 UTC, omichel commented on local_simulation_server.py
> +PORT = 2000  # Port to listen on
```suggestion
PORT = 2000 if len(sys.argv) < 2 else int(sys.argv[1])  # Port to listen on
```

2022-10-31 10:26 UTC, omichel approved these changes
Looks good to me.
Thank you.

2022-10-31 10:27 UTC, merged