Updated Docker Compose to V2
cyberbotics/webots-server pull request #25
Opened 2023-03-07 08:06 UTC by Jean-Eudes-le-retour

Docker is [deprecating Docker Compose V1](https://docs.docker.com/compose/compose-v2/) at the end of June 2023. In this PR, the code is updated to work with the new format.

Most of the changes are just to change `docker-compose` into `docker compose` but the format of some of the outputs also slightly change.

I was worrying that the progress bar wouldn't work anymore as it seems to rely on the format of the output, but after testing it seems to work fine.

2023-03-07 09:39 UTC, omichel approved these changes
Thank you.

2023-03-07 10:02 UTC, BenjaminDeleze requested changes
Nice, you should also update the documentation on the webots repository:

- webots/docs/guide/simulation-server.md
- webots/docs/guide/setup-a-webots-project-repository

and the docker example:
- webots/project/samples/howto/docker/

2023-03-07 10:02 UTC, BenjaminDeleze commented on simulation_server.py
> +                if line.startswith(f'{str(id(self))}-webots-1'):  # output from docker-compose's webots service
```suggestion
                if line.startswith(f'{str(id(self))}-webots-1'):  # output from docker compose's webots service
```

comment from line 387 should be updated as well

2023-03-08 08:41 UTC, BenjaminDeleze requested changes
comment from line 387 should be updated as wel

2023-03-08 08:57 UTC, BenjaminDeleze approved these changes
Thank you

2023-03-08 10:36 UTC, merged